version: '3.6'

x-defaults: &default
  image: node:12-alpine
  restart: always
  working_dir: /app
  command: npm run prod
  ports:
    - 80

networks:
  traefik:
    external: true

services:
  api:
    <<: *default
    volumes:
      - ./api:/app

  www:
    <<: *default
    volumes:
      - ./www:/app
    networks:
      - default
      - traefik
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.docker.network=traefik
      - traefik.backend=obolus
      - traefik.frontend.rule=Host:obolus.nicco.io